#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls import patterns, url

from ..const import DIM, GEM
from ..views.frontend import ShowPostView, show_alphabetical_posts_list


urlpatterns = patterns('dimgem.views.frontend',
    url(r'^$', 'home', name='home'),
    url(r'^dim/$', 'dimgem', {'view_name': DIM}, name=DIM),
    url(r'^gem/$', 'dimgem', {'view_name': GEM}, name=GEM),
    url(r'^dim/gramatyka/$',
        ShowPostView.as_view(template_name='posts.html',
                             template_type=DIM, category_name='Gramatyka',
                             view_name='dim_grammar'),
        name='dim_grammar'),
    url(r'^gem/gramatyka/$',
        ShowPostView.as_view(template_name='posts.html',
                             template_type=GEM, category_name='Gramatyka',
                             view_name='gem_grammar'),
        name='gem_grammar'),
    url(r'^dim/slownictwo/$',
        ShowPostView.as_view(template_name='posts.html',
                             template_type=DIM, category_name='Słownictwo',
                             view_name='dim_vocabulary'),
        name='dim_vocabulary'),
    url(r'^gem/slownictwo/$',
        ShowPostView.as_view(template_name='posts.html',
                             template_type=GEM, category_name='Słownictwo',
                             view_name='gem_vocabulary'),
        name='gem_vocabulary'),
    url(r'^dim/ciekawostki/$',
        ShowPostView.as_view(template_name='posts.html',
                             template_type=DIM, category_name='Ciekawostki',
                             view_name='dim_curiosities'),
        name='dim_curiosities'),
    url(r'^gem/ciekawostki/$',
        ShowPostView.as_view(template_name='posts.html',
                             template_type=GEM, category_name='Ciekawostki',
                             view_name='gem_curiosities'),
        name='gem_curiosities'),
    url(r'^dim/false_friends/$',
        ShowPostView.as_view(template_name='posts.html',
                             template_type=DIM,
                             category_name='False friends',
                             view_name='dim_false_friends'),
        name='dim_false_friends'),
    url(r'^gem/false_friends/$',
        ShowPostView.as_view(template_name='posts.html',
                             template_type=GEM,
                             category_name='False friends',
                             view_name='gem_false_friends'),
        name='gem_false_friends'),
    url(r'^szukaj/$', 'search', name='search'),
    url(r'^kontakt/$', 'contact', name='contact'),
    url(r'^rejestracja/$', 'register', name='register'),
    url(r'^login/$', 'log_in', name='log_in'),
    url(r'^logout/$', 'log_out', name='log_out'),
    url(r'^dodaj_post/$', 'add_post', name='add_post'),
    url(r'^poczekalnia/$', 'waiting_room', name='waiting_room'),
    url(r'^uwagi_do_postow/$', 'approve_note_to_post',
        name='approve_note_to_post'),
    url(r'^lista_alfabetyczna$', show_alphabetical_posts_list,
        name='show_alphabetical_posts_list'),
)
